app:
  env: local
  address: 127.0.0.1
  port: 8000
  timezone: Asia/Jakarta

mongo_db_remote:
  driver: mongo
  host: yourhost
  username: ""
  password: ""
  port: 27017
  database: dbname

mongo_db_local:
  driver: mongo
  host: yourhost
  username: ""
  password: ""
  port: 27017
  database: dbname

collection:
  remote:
    source: source_collection
  local:
    activity: activity_collection
    database: dabatase_collection

synclimit: 5

mail_config:
  host: hot
  port: 465
  sender_name: sender_name
  auth_email: email
  auth_password: password
  template: "files/mail-template/example.template.html"
  subject: "Tanya dosen official - Hii... __NAME__ this is daily news (__DATE_TIME__)"
